%YAML:1.0
# General stage settings
type: densification
queue_size: 20
log_to_file: 1

do_drop_planar: 1

# Flag to use bilateral filter for disparity map
use_filter_bilat: 1
# Flag to use guided filter. Only possible with stereo reconstruction
use_filter_guided: 0

compute_normals: 1

save_bilat: 0
save_dense: 1
save_guided: 0
save_imgs: 0
save_sparse: 0
save_thumb: 0
save_normals: 1
